version: '3'

services:
  frontend:
    build: ./frontend
    command: serve -s build -l 3002
    container_name: node-frontend
    restart: unless-stopped
    environment:
      - PORT=3000
    networks:
      - node  

  api:
    build: ./api
    command: npm run start
    container_name: node-api
    restart: unless-stopped
    environment:
      - PORT=3002
      - HOST=http://google.com
      - MONGO_URL=mongodb://mongo_db:27017/api
      - API_URL=http://auth:3002/api
    depends_on: 
      - mongo_db
    networks:
      - node

  auth:
    build: ./auth
    command: npm run start
    container_name:  node-auth
    restart: unless-stopped
    environment:
      - PORT=3001
      - HOST=http://google.com
      - MONGO_URL=mongodb://mongodb_auth:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - mongodb_auth
    networks:
      - node  

  mongodb_auth:
    image: mongo:latest
    container_name: node-api-db-auth
    volumes:
      - mongodb_auth:/data/db
    networks:
      - node  

  nginx:
    image: nginx:stable-alpine
    container_name: node-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - node

  mongo_db:
    image: mongo:latest
    container_name: node-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - node

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  node:
    driver: bridge  